<?php
namespace ApiGoat\Mcp\Tools;

use ApiGoat\Mcp\McpIdentity;
use ApiGoat\Mcp\ToolError;
use ApiGoat\Sessions\AuthySession;

/**
 * gc_identity_update — let the model teach this server how it is referred to.
 *
 * The routing preamble (McpIdentity::preamble) lists the terms that send a
 * request to this project. When the user has to pick the server by hand, or
 * calls the project by a name the list lacks, the model adds the term here
 * and the next conversation routes on its own. Writes go to the editable
 * overlay config/mcp.identity.local.php (never regenerated by gc build, not
 * shipped by gc deploy); the schema's name stays authoritative — only
 * `about` and the keyword list move. Same confirm gate as crm_create.
 */
class GcIdentityUpdate implements \ApiGoat\Mcp\McpTool
{
    public function name(): string { return 'gc_identity_update'; }

    public function description(): string
    {
        return 'Improve how requests get routed to THIS server: add or remove routing keywords and refine '
             . 'the one-line "about" of the project identity announced at the start of every conversation. '
             . 'Call it when the user had to tell you to use this server, or used a name/term for this '
             . 'project that the identity does not list. Without confirm:true nothing is written: the call '
             . 'echoes the resulting identity — show it to the user and re-call with confirm:true once they '
             . 'approve. Changes persist in config/mcp.identity.local.php on this host; the name cannot change here.';
    }

    public function inputSchema(): array
    {
        return ['type' => 'object', 'properties' => [
            'add_keywords'    => ['type' => 'array', 'items' => ['type' => 'string'],
                'description' => 'Routing terms to add (brand, client, product or domain words the user actually used); lowercased and de-duplicated'],
            'remove_keywords' => ['type' => 'array', 'items' => ['type' => 'string'],
                'description' => 'Terms that wrongly route requests here'],
            'about'           => ['type' => 'string', 'maxLength' => McpIdentity::ABOUT_MAX,
                'description' => 'Replacement one-line description (max ' . McpIdentity::ABOUT_MAX . ' chars); omit to keep the current one'],
            'confirm'         => ['type' => 'boolean',
                'description' => 'must be true to write; show the user the pending identity first'],
        ]];
    }

    /** Admins, or a session that may write the project Config, may teach the router. */
    public function requiredRight(): ?array { return ['Config', 'w']; }

    public function handle(array $args, AuthySession $session): array
    {
        $built = McpIdentity::readBuilt();
        if ($built === null) {
            throw new ToolError('This project has no MCP identity (with_mcp is not declared) — nothing to update.', [], 'not_found');
        }
        $add    = McpIdentity::keywordList($args['add_keywords'] ?? []);
        $remove = McpIdentity::keywordList($args['remove_keywords'] ?? []);
        $about  = isset($args['about']) && is_scalar($args['about']) ? trim((string) $args['about']) : null;
        if ($add === [] && $remove === [] && ($about === null || $about === '')) {
            throw new ToolError('Nothing to change: pass add_keywords, remove_keywords and/or about.', [], 'validation');
        }
        if ($about !== null && mb_strlen($about) > McpIdentity::ABOUT_MAX) {
            throw new ToolError('about must be at most ' . McpIdentity::ABOUT_MAX . ' characters.', [], 'validation');
        }
        if (array_intersect($add, $remove) !== []) {
            throw new ToolError('A keyword cannot be both added and removed: ' . implode(', ', array_intersect($add, $remove)), [], 'validation');
        }

        $local = McpIdentity::readLocal() ?? ['about' => '', 'keywords' => [], 'removed' => []];
        // Adding un-removes; removing un-adds — the overlay stays minimal.
        $local['keywords'] = array_values(array_diff(array_unique(array_merge($local['keywords'], $add)), $remove));
        $local['removed']  = array_values(array_diff(array_unique(array_merge($local['removed'], $remove)), $add));
        if ($about !== null && $about !== '') {
            $local['about'] = $about === $built['about'] ? '' : $about;
        }
        $effective = McpIdentity::merge($built, $local);

        $view = [
            'identity' => ['name' => $effective['name'], 'about' => $effective['about'], 'keywords' => $effective['keywords']],
            'change'   => ['added' => $add, 'removed' => $remove] + ($about !== null && $about !== '' ? ['about' => $about] : []),
        ];
        if (empty($args['confirm'])) {
            throw new ToolError(
                'Nothing written yet — show the user this resulting identity and re-call with confirm:true once they approve: '
                . json_encode($view, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
                [],
                'bad_request'
            );
        }
        $file = McpIdentity::writeLocal($local);
        $view['saved'] = true;
        $view['file']  = basename($file);
        $view['note']  = 'Takes effect at the next MCP initialize (new conversation). Promote into the schema with `gc mcp --setup`.';
        return ['content' => [['type' => 'text', 'text' => json_encode($view, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)]]];
    }
}
