<?php
namespace ApiGoat\Mcp;

/**
 * Build-time MCP tool-list stamp: config/Built/mcp.version.php.
 *
 * `gc build` calls write() with the tool names the server exposes; the stamp
 * carries a version derived from that list plus what changed since the
 * previous *different* list. McpServer reads it on initialize to report
 * serverInfo.version and to prefix the instructions with a "what's new"
 * notice — the only signal that reaches connectors already installed on a
 * client (the transport is stateless POST, so tools/list_changed cannot be
 * pushed). A rebuild with an unchanged tool list keeps the previous stamp
 * untouched, so the notice persists until the next real change.
 */
final class VersionStamp
{
    public const FILE = 'config/Built/mcp.version.php';

    /** @return array{version:string,tools:string[],changed_at:string,added:string[],removed:string[],previous_version:?string}|null */
    public static function read(?string $baseDir = null): ?array
    {
        $path = self::path($baseDir);
        if ($path === null || !is_file($path)) {
            return null;
        }
        $v = @include $path;
        return (is_array($v) && isset($v['version'], $v['tools']) && is_array($v['tools'])) ? $v : null;
    }

    /**
     * Compare $toolNames with the stored stamp and persist a new one when the
     * list changed. Returns the effective stamp plus 'changed' (bool).
     *
     * @param string[] $toolNames
     * @return array{stamp:array,changed:bool,path:string}
     */
    public static function write(string $baseDir, array $toolNames, ?string $now = null): array
    {
        $names = array_values(array_unique(array_filter(array_map('strval', $toolNames), fn($n) => $n !== '')));
        sort($names, SORT_STRING);
        $path = self::path($baseDir);
        $prev = self::read($baseDir);

        if ($prev !== null && $prev['tools'] === $names) {
            return ['stamp' => $prev, 'changed' => false, 'path' => $path];
        }

        $now   = $now ?? date('Y-m-d H:i');
        $stamp = [
            'version'          => date('Y.m.d', strtotime($now) ?: time()) . '-' . substr(sha1(implode(',', $names)), 0, 6),
            'tools'            => $names,
            'changed_at'       => $now,
            // The very first stamp announces nothing: every tool would be "new".
            'added'            => $prev === null ? [] : array_values(array_diff($names, $prev['tools'])),
            'removed'          => $prev === null ? [] : array_values(array_diff($prev['tools'], $names)),
            'previous_version' => $prev['version'] ?? null,
        ];

        $php = "<?php\n// AUTO-GENERATED by gc build (ApiGoat\\Mcp\\VersionStamp) — do not edit.\n"
            . "// MCP tool-list version + what changed since the previous tool list;\n"
            . "// surfaced by McpServer::initialize (serverInfo.version, instructions).\n"
            . 'return ' . var_export($stamp, true) . ";\n";
        if (!is_dir(dirname($path))) {
            @mkdir(dirname($path), 0775, true);
        }
        if (@file_put_contents($path, $php) === false) {
            throw new \RuntimeException("Cannot write MCP version stamp: {$path}");
        }
        return ['stamp' => $stamp, 'changed' => true, 'path' => $path];
    }

    /** Model-facing notice for the instructions prefix; null when nothing changed. */
    public static function whatsNew(?array $stamp): ?string
    {
        if ($stamp === null || (empty($stamp['added']) && empty($stamp['removed']))) {
            return null;
        }
        $parts = [];
        if (!empty($stamp['added'])) {
            $parts[] = 'new tools: ' . implode(', ', $stamp['added']);
        }
        if (!empty($stamp['removed'])) {
            $parts[] = 'removed tools: ' . implode(', ', $stamp['removed']);
        }
        return 'SERVER UPDATE (' . ($stamp['changed_at'] ?? '') . ', version ' . ($stamp['version'] ?? '?') . '): '
            . implode('; ', $parts) . '. If the user has not been told about this update in this conversation, '
            . 'mention it once in a short sentence, then carry on with their request.';
    }

    private static function path(?string $baseDir): ?string
    {
        $base = $baseDir ?? (defined('_BASE_DIR') ? _BASE_DIR : null);
        if ($base === null || $base === '') {
            return null;
        }
        return rtrim($base, '/\\') . '/' . self::FILE;
    }
}
